
process.abort();
process.chdir();
process.cpuUsage();
process.cwd();
process.disconnect();
process.dlopen();
process.emitWarning();
process.emitWarning();
process.getegid();
process.geteuid();
process.getgid();
process.getgroups();
process.getuid();
process.hasUncaughtExceptionCaptureCallback();
process.hrtime();
process.hrtime.bigint();
process.initgroups();
process.kill();
process.memoryUsage();
process.nextTick(x => x);
process.report.getReport();
process.report.writeReport();
process.resourceUsage();
process.send("", x => x);
process.setegid();
process.seteuid();
process.setgid();
process.setgroups();
process.setuid();
process.setUncaughtExceptionCaptureCallback();
process.umask();
process.uptime();
process.exit();
